version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: car_rental_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - car_rental_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "root", "-prootpass" ]
      interval: 5s
      retries: 10
      start_period: 10s

  booking-service:
    build: ./booking-service
    container_name: booking-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookingdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: bookinguser
      SPRING_DATASOURCE_PASSWORD: bookingpass
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - car_rental_net

  car-pricing-service:
    build: ./car-pricing-service
    container_name: car-pricing-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/car_pricing_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: pricinguser
      SPRING_DATASOURCE_PASSWORD: pricingpass
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - car_rental_net

  driving-license-service:
    build: ./driving-license-service
    container_name: driving-license-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/driving_license_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: licenseuser
      SPRING_DATASOURCE_PASSWORD: licensepass
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - car_rental_net

volumes:
  mysql-data:

networks:
  car_rental_net:
    driver: bridge
